"""Re-generate migration for password hashing

Revision ID: 38d90c6735e0
Revises: 
Create Date: 2025-06-19 17:29:49.488243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38d90c6735e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransactionHistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_AccountID'))
        batch_op.drop_index(batch_op.f('idx_TransactionDate'))

    op.drop_table('TransactionHistory')
    with op.batch_alter_table('AccountLossReport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_AccountID'))
        batch_op.drop_index(batch_op.f('idx_CustomerID'))

    op.drop_table('AccountLossReport')
    with op.batch_alter_table('TransactionHistoryInquiryRequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_AccountID'))
        batch_op.drop_index(batch_op.f('idx_CustomerID'))
        batch_op.drop_index(batch_op.f('idx_RequestDateTime'))

    op.drop_table('TransactionHistoryInquiryRequest')
    op.drop_table('HousingSubscriptionNotice')
    with op.batch_alter_table('LoanExtensionApplication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_AccountID'))
        batch_op.drop_index(batch_op.f('idx_CustomerID'))

    op.drop_table('LoanExtensionApplication')
    with op.batch_alter_table('ConsultationHistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ConsultationDateTime'))
        batch_op.drop_index(batch_op.f('idx_CustomerID'))

    op.drop_table('ConsultationHistory')
    with op.batch_alter_table('LoanAccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('AccountNumber'))
        batch_op.drop_index(batch_op.f('idx_CustomerID'))

    op.drop_table('LoanAccount')
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('BusinessRegNo'))
        batch_op.drop_column('RegistrationDate')
        batch_op.drop_column('BusinessRegNo')
        batch_op.drop_column('RepresentativeName')
        batch_op.drop_column('ModificationDate')

    with op.batch_alter_table('DepositWithdrawalAccount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PasswordHash', sa.String(length=128), nullable=True, comment='계좌 비밀번호 (암호화됨)'))
        batch_op.drop_index(batch_op.f('idx_CustomerID'))
        batch_op.drop_column('ClosingDate')
        batch_op.drop_column('TransStartDate')
        batch_op.drop_column('Password')
        batch_op.drop_column('TransEndDate')
        batch_op.drop_column('OpeningDate')

    with op.batch_alter_table('NotificationServiceApplication', schema=None) as batch_op:
        batch_op.alter_column('CustomerID',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='Customer 테이블의 외래 키',
               existing_nullable=False)
        batch_op.alter_column('AccountID',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='DepositWithdrawalAccount 테이블의 외래 키',
               existing_nullable=False)
        batch_op.alter_column('ShowBalanceYn',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_comment='잔액표시여부(Y,N)',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_AccountID'))
        batch_op.drop_index(batch_op.f('idx_CustomerID'))
        batch_op.drop_constraint(batch_op.f('NotificationServiceApplication_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('NotificationFrequency')
        batch_op.drop_column('CancellationDate')
        batch_op.drop_column('AutoTransferNightYn')
        batch_op.drop_column('NotificationConditions')
        batch_op.drop_column('NotificationScope')
        batch_op.drop_column('FeeType')
        batch_op.drop_column('ChangeDate')
        batch_op.drop_column('FeeAccountID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NotificationServiceApplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FeeAccountID', mysql.VARCHAR(length=10), nullable=True, comment='수수료 부과 계좌 (DepositWithdrawalAccount 테이블의 외래 키)'))
        batch_op.add_column(sa.Column('ChangeDate', mysql.DATETIME(), nullable=True, comment='변경 일시'))
        batch_op.add_column(sa.Column('FeeType', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True, comment='과금종류(종량제:1, 정액제:2)'))
        batch_op.add_column(sa.Column('NotificationScope', mysql.CHAR(length=1), nullable=True, comment='수신범위설정 여부(Y, N)'))
        batch_op.add_column(sa.Column('NotificationConditions', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True, comment='알림 조건 (예: 금액 이상/이하)'))
        batch_op.add_column(sa.Column('AutoTransferNightYn', mysql.CHAR(length=1), nullable=True, comment='자동이체 새벽수신여부(Y,N)'))
        batch_op.add_column(sa.Column('CancellationDate', mysql.DATETIME(), nullable=True, comment='해지 일시'))
        batch_op.add_column(sa.Column('NotificationFrequency', mysql.VARCHAR(length=10), nullable=True, comment='알림 빈도: 실시간(1), 지연(0)'))
        batch_op.create_foreign_key(batch_op.f('NotificationServiceApplication_ibfk_3'), 'DepositWithdrawalAccount', ['FeeAccountID'], ['AccountID'])
        batch_op.create_index(batch_op.f('idx_CustomerID'), ['CustomerID'], unique=False)
        batch_op.create_index(batch_op.f('idx_AccountID'), ['AccountID'], unique=False)
        batch_op.alter_column('ShowBalanceYn',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_comment='잔액표시여부(Y,N)',
               existing_nullable=True)
        batch_op.alter_column('AccountID',
               existing_type=mysql.VARCHAR(length=10),
               comment='DepositWithdrawalAccount 테이블의 외래 키',
               existing_nullable=False)
        batch_op.alter_column('CustomerID',
               existing_type=mysql.VARCHAR(length=10),
               comment='Customer 테이블의 외래 키',
               existing_nullable=False)

    with op.batch_alter_table('DepositWithdrawalAccount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('OpeningDate', mysql.VARCHAR(length=8), nullable=True, comment='계좌 개설일(YYYYMMDD)'))
        batch_op.add_column(sa.Column('TransEndDate', mysql.VARCHAR(length=8), nullable=True, comment='거래 가능 종료일(YYYYMMDD)'))
        batch_op.add_column(sa.Column('Password', mysql.VARCHAR(length=6), nullable=True, comment='계좌 비밀번호 (암호화 고려)'))
        batch_op.add_column(sa.Column('TransStartDate', mysql.VARCHAR(length=8), nullable=True, comment='거래 가능 시작일(YYYMMDD)'))
        batch_op.add_column(sa.Column('ClosingDate', mysql.VARCHAR(length=8), nullable=True, comment='계좌 해지일(YYYYMMDD)'))
        batch_op.create_index(batch_op.f('idx_CustomerID'), ['CustomerID'], unique=False)
        batch_op.drop_column('PasswordHash')

    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ModificationDate', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('RepresentativeName', mysql.VARCHAR(length=50), nullable=True, comment='법인 고객의 대표자 이름'))
        batch_op.add_column(sa.Column('BusinessRegNo', mysql.VARCHAR(length=20), nullable=True, comment='법인 고객의 사업자등록번호'))
        batch_op.add_column(sa.Column('RegistrationDate', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True, comment='고객 등록일시'))
        batch_op.create_index(batch_op.f('BusinessRegNo'), ['BusinessRegNo'], unique=True)

    op.create_table('LoanAccount',
    sa.Column('AccountID', mysql.VARCHAR(length=10), nullable=False, comment='대출 계좌 고유 식별자(10000001)'),
    sa.Column('CustomerID', mysql.VARCHAR(length=10), nullable=False, comment='Customer 테이블의 외래 키'),
    sa.Column('AccountNumber', mysql.VARCHAR(length=20), nullable=False, comment='계좌 번호 (고유)'),
    sa.Column('OpeningDate', mysql.VARCHAR(length=8), nullable=True, comment='계좌 개설일(YYYYMMDD)'),
    sa.Column('ClosingDate', mysql.VARCHAR(length=8), nullable=True, comment='계좌 해지일(YYYYMMDD)'),
    sa.Column('AccountStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='계좌 상태: 활성(1), 비활성(9), 해지(0)'),
    sa.Column('LoanType', mysql.VARCHAR(length=50), nullable=True, comment='대출 종류'),
    sa.Column('LoanName', mysql.VARCHAR(length=50), nullable=True, comment='대출 상품명'),
    sa.Column('LoanAmount', mysql.DECIMAL(precision=15, scale=2), nullable=True, comment='대출 금액'),
    sa.Column('LoanStartDate', mysql.VARCHAR(length=8), nullable=True, comment='대출 시작일(YYYYMMDD)'),
    sa.Column('LoanEndDate', mysql.VARCHAR(length=8), nullable=True, comment='대출 종료일(YYYYMMDD)'),
    sa.Column('LoanMaturity', mysql.VARCHAR(length=8), nullable=True, comment='대출 만기일(YYYYMMDD'),
    sa.Column('ApplicationDate', mysql.DATETIME(), nullable=True, comment='신청일'),
    sa.Column('ProcessingStatus', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='처리 상태: 신청(1), 검토중(2), 승인(3), 거절(9)'),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customer.CustomerID'], name='LoanAccount_ibfk_1'),
    sa.PrimaryKeyConstraint('AccountID'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('LoanAccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_CustomerID'), ['CustomerID'], unique=False)
        batch_op.create_index(batch_op.f('AccountNumber'), ['AccountNumber'], unique=True)

    op.create_table('ConsultationHistory',
    sa.Column('ConsultationID', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='상담 이력 고유 식별자'),
    sa.Column('CustomerID', mysql.VARCHAR(length=10), nullable=True, comment='Customer 테이블의 외래 키'),
    sa.Column('ConsultationDateTime', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True, comment='상담 일시'),
    sa.Column('ConsultationChannel', mysql.VARCHAR(length=20), nullable=True, comment='상담 채널: 챗봇(1), 상담원(0)'),
    sa.Column('ConsultationContent', mysql.TEXT(), nullable=True, comment='상담 내용'),
    sa.Column('ProcessingResult', mysql.TEXT(), nullable=True, comment='처리 결과'),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customer.CustomerID'], name=op.f('ConsultationHistory_ibfk_1')),
    sa.PrimaryKeyConstraint('ConsultationID'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ConsultationHistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_CustomerID'), ['CustomerID'], unique=False)
        batch_op.create_index(batch_op.f('idx_ConsultationDateTime'), ['ConsultationDateTime'], unique=False)

    op.create_table('LoanExtensionApplication',
    sa.Column('ApplicationID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='대출 기한 연장 신청 고유 식별자'),
    sa.Column('CustomerID', mysql.VARCHAR(length=10), nullable=False, comment='Customer 테이블의 외래 키'),
    sa.Column('AccountID', mysql.VARCHAR(length=10), nullable=False, comment='LoanAccount 테이블의 외래 키'),
    sa.Column('ApplicationDate', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True, comment='신청 일시'),
    sa.Column('RequestedExtensionPeriod', mysql.VARCHAR(length=10), nullable=False, comment='연장 희망 기간'),
    sa.Column('ApplicationReason', mysql.TEXT(), nullable=True, comment='신청 사유'),
    sa.Column('ProcessingStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='처리 상태: 신청(1), 검토중(2), 승인(0), 거절(9)'),
    sa.Column('ProcessingDate', mysql.DATETIME(), nullable=True, comment='처리 일시'),
    sa.Column('ProcessingResultDetails', mysql.TEXT(), nullable=True, comment='처리 결과 상세 내용'),
    sa.ForeignKeyConstraint(['AccountID'], ['LoanAccount.AccountID'], name=op.f('LoanExtensionApplication_ibfk_2')),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customer.CustomerID'], name=op.f('LoanExtensionApplication_ibfk_1')),
    sa.PrimaryKeyConstraint('ApplicationID'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('LoanExtensionApplication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_CustomerID'), ['CustomerID'], unique=False)
        batch_op.create_index(batch_op.f('idx_AccountID'), ['AccountID'], unique=False)

    op.create_table('HousingSubscriptionNotice',
    sa.Column('NoticeID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='주택 청약 안내 고유 식별자'),
    sa.Column('NoticeTitle', mysql.VARCHAR(length=255), nullable=False, comment='안내 제목'),
    sa.Column('NoticeContent', mysql.TEXT(), nullable=False, comment='안내 내용'),
    sa.Column('RegistrationDate', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True, comment='등록 일시'),
    sa.Column('ModificationDate', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('NoticeID'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('TransactionHistoryInquiryRequest',
    sa.Column('RequestID', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='거래 내역 조회 요청 고유 식별자'),
    sa.Column('CustomerID', mysql.VARCHAR(length=10), nullable=False, comment='Customer 테이블의 외래 키'),
    sa.Column('AccountID', mysql.VARCHAR(length=10), nullable=False, comment='DepositWithdrawalAccount 테이블의 외래 키'),
    sa.Column('RequestDateTime', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True, comment='요청 일시'),
    sa.Column('InquiryStartDate', mysql.VARCHAR(length=10), nullable=False, comment='조회 시작일'),
    sa.Column('InquiryEndDate', mysql.VARCHAR(length=10), nullable=False, comment='조회 종료일'),
    sa.Column('RequestChannel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='요청 채널: 챗봇(1), 상담원(0)'),
    sa.Column('ProcessingMethod', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='처리 방식: 팩스(1), 이메일(0)'),
    sa.Column('EmailAddress', mysql.VARCHAR(length=100), nullable=True, comment='이메일 주소'),
    sa.Column('FaxNumber', mysql.VARCHAR(length=20), nullable=True, comment='팩스 번호'),
    sa.Column('ProcessingStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='처리 상태: 신청(1), 처리중(9), 완료(0), 실패(8)'),
    sa.Column('ProcessingDateTime', mysql.DATETIME(), nullable=True, comment='처리 일시'),
    sa.Column('ErrorDetails', mysql.TEXT(), nullable=True, comment='오류 상세 내용'),
    sa.ForeignKeyConstraint(['AccountID'], ['DepositWithdrawalAccount.AccountID'], name=op.f('TransactionHistoryInquiryRequest_ibfk_2')),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customer.CustomerID'], name=op.f('TransactionHistoryInquiryRequest_ibfk_1')),
    sa.PrimaryKeyConstraint('RequestID'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('TransactionHistoryInquiryRequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_RequestDateTime'), ['RequestDateTime'], unique=False)
        batch_op.create_index(batch_op.f('idx_CustomerID'), ['CustomerID'], unique=False)
        batch_op.create_index(batch_op.f('idx_AccountID'), ['AccountID'], unique=False)

    op.create_table('AccountLossReport',
    sa.Column('ReportID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='계좌 분실 신고 고유 식별자'),
    sa.Column('CustomerID', mysql.VARCHAR(length=10), nullable=False, comment='Customer 테이블의 외래 키'),
    sa.Column('AccountID', mysql.VARCHAR(length=10), nullable=False, comment='DepositWithdrawalAccount 테이블의 외래 키'),
    sa.Column('lostRegiType', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='분실신고자(본인:0, 대리인:1)'),
    sa.Column('LostRegiTelno', mysql.VARCHAR(length=15), nullable=True, comment='분실신고 연락처'),
    sa.Column('LostRegiName', mysql.VARCHAR(length=50), nullable=True, comment='분실신고등록 이름'),
    sa.Column('autoTransYn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='자동화기기 거래 (1:가능, 0: 불가)'),
    sa.Column('ReportDate', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True, comment='분실 신고 일시'),
    sa.Column('ProcessingStatus', mysql.VARCHAR(length=10), nullable=True, comment='처리 상태: 신청(1), 처리중(9), 완료(2), 취소(0)'),
    sa.Column('CancellationRequestDate', mysql.DATETIME(), nullable=True, comment='취소 요청 일시'),
    sa.Column('CancellationReason', mysql.TEXT(), nullable=True, comment='취소 사유'),
    sa.ForeignKeyConstraint(['AccountID'], ['DepositWithdrawalAccount.AccountID'], name=op.f('AccountLossReport_ibfk_2')),
    sa.ForeignKeyConstraint(['CustomerID'], ['Customer.CustomerID'], name=op.f('AccountLossReport_ibfk_1')),
    sa.PrimaryKeyConstraint('ReportID'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('AccountLossReport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_CustomerID'), ['CustomerID'], unique=False)
        batch_op.create_index(batch_op.f('idx_AccountID'), ['AccountID'], unique=False)

    op.create_table('TransactionHistory',
    sa.Column('TransactionID', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='거래 내역 고유 식별자'),
    sa.Column('AccountID', mysql.VARCHAR(length=10), nullable=False, comment='DepositWithdrawalAccount 테이블의 외래 키'),
    sa.Column('TransactionDate', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True, comment='거래 일시'),
    sa.Column('TransactionAmount', mysql.DECIMAL(precision=15, scale=2), nullable=False, comment='거래 금액'),
    sa.Column('TransactionType', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='거래 유형: 입금(1), 출금(2), 이체(3)'),
    sa.Column('CounterpartyAccountNumber', mysql.VARCHAR(length=20), nullable=True, comment='상대방 계좌 번호'),
    sa.Column('TransactionDetails', mysql.VARCHAR(length=255), nullable=True, comment='거래 상세 내용'),
    sa.Column('Balance', mysql.DECIMAL(precision=15, scale=2), nullable=True, comment='거래 후 잔액'),
    sa.Column('Note', mysql.VARCHAR(length=100), nullable=True, comment='거래 관련 메모'),
    sa.ForeignKeyConstraint(['AccountID'], ['DepositWithdrawalAccount.AccountID'], name=op.f('TransactionHistory_ibfk_1')),
    sa.PrimaryKeyConstraint('TransactionID'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('TransactionHistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_TransactionDate'), ['TransactionDate'], unique=False)
        batch_op.create_index(batch_op.f('idx_AccountID'), ['AccountID'], unique=False)

    # ### end Alembic commands ###
