server {
    listen 80;
    server_name _; # 실제 서비스 시 EC2 IP 또는 도메인으로 변경

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ec2-user/multimodal_app_deploy/src/multimodal_app.sock;
        # 변경된 소켓 경로: /home/ec2-user/multimodal_app_deploy/src/<프로젝트명>.sock
    }

    location /static/ {
        alias /home/ec2-user/multimodal_app_deploy/src/app/static/;
        # 변경된 정적 파일 경로
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}